name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Run JavaScript file
        run: node your_script.js
        env:
          EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
          EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}

      - name: Verify secrets
        run: |
          echo "EMAILJS_USER_ID starts with: "${{secrets.EMAILJS_USER_ID }} | sed 's/./& /g'
        env:
          SECRETS_EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
          SECRETS_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          SECRETS_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}