name: GitHub Actions Secret Example

on:
  push:
    branches:
      - master

jobs:
  example-job:
    runs-on: windows-latest

    steps:

      - name: Verify secrets
        run: |
          echo "EMAILJS_USER_ID starts with:" ${{secrets.EMAILJS_USER_ID}} | sed 's/./& /g'
          echo "EMAILJS_SERVICE_ID starts with:" ${{secrets.EMAILJS_SERVICE_ID}} | sed 's/./& /g'
          echo "EMAILJS_TEMPLATE_ID starts with:" ${{secrets.EMAILJS_TEMPLATE_ID}} | sed 's/./& /g'
