name: GitHub Actions Secret Example

on:
  push:
    branches:
      - master

jobs:
  example-job:
    runs-on: windows-latest

    steps:

      - name: Verify secrets
        run: |
          echo "EMAILJS_USER_ID starts with: ${SECRETS_EMAILJS_USER_ID:0:4}******"
          echo "EMAILJS_SERVICE_ID starts with: ${SECRETS_EMAILJS_SERVICE_ID:0:4}******"
          echo "EMAILJS_TEMPLATE_ID starts with: ${SECRETS_EMAILJS_TEMPLATE_ID:0:4}******"
